development:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Use Amazon S3 fpr production environment
# gem "aws-sdk-s3", require: false
amazon:
  service: S3
  access_key_id: <%= ENV['FILIO_AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['FILIO_AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['FILIO_AWS_REGION'] %> # e.g. 'us-east-1'
  bucket: <%= ENV['FILIO_BUCKET_NAME'] %>